---
- name: Deploying CakePHP 3.x
  command: composer -sdev -n create-project cakephp/app app chdir=/vagrant/apps/ creates=/vagrant/apps/app

- name: Create Symlink
  action: file src=/vagrant/apps/app dest=/vagrant/www state=link
  notify:
    - reload nginx
    - restart php-fpm
