---
nginx_http_params:
  disable_symlinks: off
  access_log: /var/log/nginx/access.log
  error_log: /var/log/nginx/error.log

nginx_sites:
  - file_name: default
    listen: 80
    server_name: localhost
    root: /usr/share/nginx/www
    index: index.html
    locations:
      - name: /
        lines:
          - "try_files $uri $uri/ /index.html"
      - name: /images/
        lines:
          - "root /usr/share"
          - "autoindex off"

  #CakePHP app server
  - file_name: app
    listen: 80
    server_name: app.dev
    root: /vagrant/www
    access_log: /var/log/nginx/app-access.log
    error_log: /var/log/nginx/app-error.log
    index: index.php
    locations:
      - name: /
        lines:
          - "try_files $uri $uri/ /index.php?$uri&$args"
          - "expires max"
          - "access_log off"
      - name: "~ \\.php$"
        lines:
          - "fastcgi_pass unix:/var/run/php/php7.0-fpm.sock"
          - "include fastcgi_params"
      - name: "~ ^/(.+?)/(.*)$"
        lines:
          - "try_files $uri $uri/ /$1/index.php?$2&$args"
          - "expires max"
          - "access_log off"
      - name: "~ ^/(.+?)/(.+\\.php)$"
        lines:
          - "fastcgi_pass unix:/var/run/php/php7.0-fpm.sock"
          - "include fastcgi_params"

  # Redirect www.app.dev to app.dev
  - file_name: www.app
    listen: 80
    server_name: www.app.dev
    return: "301 http://app.dev$uri"
    locations: []
