---
# Mailcatcher
- name: MailCatcher | Packages dependencies
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - software-properties-common
    - libsqlite3-dev
    - ruby2.0
    - ruby2.0-dev
  become: yes

- name: Symlink exists for Ruby 2.0
  file: src=/usr/bin/ruby2.0 dest=/usr/local/bin/ruby state=link
  become: yes

- name: Symlink exists for Ruby Gems 2.0
  file: src=/usr/bin/gem2.0 dest=/usr/local/bin/gem state=link
  become: yes

- name: MailCatcher | Install MailCatcher
  command: gem install mailcatcher
  become: yes

- name: MailCatcher | Configure FPM PHP.ini
  command: sed -ir "s/;\?sendmail_path =.*/sendmail_path = \/usr\/bin\/env \/usr\/local\/bin\/catchmail/" /etc/php/7.0/fpm/php.ini
  become: yes

- name: MailCatcher | Configure CLI PHP.ini
  command: sed -ir "s/;\?sendmail_path =.*/sendmail_path = \/usr\/bin\/env \/usr\/local\/bin\/catchmail/" /etc/php/7.0/cli/php.ini
  become: yes
