---
- name: Add PPA
  apt_repository: repo="ppa:ondrej/php"

- name: Install PHP and Dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - php7.0-cli
    - php7.0-common
    - php7.0-curl
    - php7.0-fpm
    - php7.0-gd
    - php7.0-geoip
    - php7.0-gmp
    - php7.0-imagick
    - php7.0-intl
    - php7.0-json
    - php7.0-mbstring
    - php7.0-mcrypt
    - php7.0-memcache
    - php7.0-memcached
    - php7.0-mysql
    - php7.0-opcache
    - php7.0-redis
    - php7.0-sqlite3
    - php7.0-xdebug

- name: Install Composer
  get_url: url=https://getcomposer.org/composer.phar dest=/usr/local/bin/composer mode=0755 validate_certs=no

- name: Copy pool configuration
  template: src=www.conf dest=/etc/php/7.0/fpm/pool.d/
  notify: restart php-fpm

- name: Start php-fpm
  service: name=php7.0-fpm state=started enabled=true
