---
- name: Deploys the whole software stack for a CakePHP application
  hosts: development
  user: vagrant
  become: yes

  roles:
    - system
    - php
    - repleo.nginx
    - percona
    - redis
    - memcached
    - cakephp
